### PR TITLE
Multiple Bot Types, Rarity, sets 4 + 5, folder support and more.

### PR DESCRIPTION
**Pull request by druerridge**
Please hold off on merging - I'm still running tests.

### CODE REVIEW

**Comment by druerridge** [comment]
Tested and ready to merge!

I can definitely do more to update the readme, but it is correct, and the functionality is all working so I'd love to get this merged in with all the improvements.

**Comment by ZacharyRSmith** [comment]
thanks much!

**Comment by ZacharyRSmith** [comment]
@druerridge at this point, you practically own the repo. Do you want me to transfer ownership? The only issue i can see is if someone tries to go to github.com/zacharyrsmith/dreamborn_to_draftmancer , but i think it would redirect based on: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by druerridge** [comment]
Sure, go for it!

**Comment by ZacharyRSmith** [comment]
ah, it seems i can't transfer ownership because of your fork:

Screen Shot 2024-09-14 at 11 24 14 AM

i could transfer ownership after you rename or delete your fork, but probably it just makes sense to update my repo to make it very obvious that it's deprecated in favor of your fork. So, i'll do that

**Comment by ZacharyRSmith** [comment]
i just updated the readme to point people to your repo. Please lemme know if you think there's anything else that would help.

**Comment by druerridge** [comment]
It's live as a website now! at https://www.cubecana.com/ 
If you know any front-end devs, please send help, it's just co-pilot and my html skills from a summer camp in 2002 :P

**Comment by ZacharyRSmith** [comment]
noice! I just dropped a message in the philly lorcana discord

have you thought of adding lorcanito.com to step 3? It automates most stuff so much easier than tabletop sim

**Comment by druerridge** [comment]
I'm going to do inktable.net so why not! I'll add it to the to do list.

**Pull request merged**
